name: unfaithfulcots
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  # Core scientific stack
  - numpy
  - pyyaml
  # PyTorch (CPU by default). For GPU, also add pytorch-cuda below.
  - pytorch
  # Optional for NVIDIA GPU (uncomment the next line if you have CUDA 12.1)
  # - pytorch-cuda=12.1
  - pip:
      - transformers>=4.44
      - accelerate>=0.33
      - huggingface_hub>=0.24
